/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spark_gcs;

import org.apache.spark.sql.SparkSession;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        SparkSession spark = SparkSession.builder()
            .appName("Simple Application")
            .config("spark.hadoop.fs.s3a.access.key", "AKIA2S4AYDOOF7VZ3AE2")
            .config("spark.hadoop.fs.s3a.secret.key", "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")
            .config("spark.hadoop.fs.s3a.endpoint", "s3.amazonaws.com")
            .getOrCreate();

        
        Dataset<Row> df = spark.read().format("csv").option("header", "true").load("s3a://hiep-bk-1/NASDAQ_1962-2024.csv");
        df.show();
    }
}
