version: '3.9'



services:
  # clickhouse:
  #   image: clickhouse/clickhouse-server
  #   user: "101:101"
  #   container_name: clickhouse
  #   hostname: clickhouse
  #   volumes:
  #     - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
  #     - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
  #     - ${PWD}/fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #   ports:
  #     - "127.0.0.1:8123:8123"
  #     - "127.0.0.1:9000:9000"
  #   depends_on:
  #     - postgres

  sql-server:
    container_name: sql-server
    hostname: sqlserver
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
      - MSSQL_SA_PASSWORD=Hiep@1234
    volumes:
      - data:/var/opt/mssql
      - log:/var/opt/mssql/log
      - backup:/var/opt/mssql/backup

    restart: on-failure
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit
      interval: 30s
      timeout: 30s
      retries: 3

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clickhouse_pg_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical" #required for MaterializedPostgreSQL

volumes:
  data: {}
  pgdata:
  log: {}
  backup: {}