
version: 2


# Test
models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

# Source  
# sources:
#   - name: raw_layer
#     schema: raw_layer
#     tables:
#       - name: customers
#         description: "Customers data from raw layer"